/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIew;

import DAO.CabekaDAO;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import model.Cabeka;
import model.Guru;
import model.Siswa;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;

/**
 *
 * @author TUF GAMING F15
 */
public class CabekaView extends javax.swing.JFrame implements DataCallback {
    private ArrayList<JTextField> textFields;    
    private ArrayList<JTextArea> textArea;

    CabekaDAO dao = new CabekaDAO();
    PreparedStatement ps;
    ResultSet rs;
    Siswa siswa = new Siswa();
    Cabeka cabeka = new Cabeka();
    JasperReport jasRep;
    JasperPrint jasPrint;
    JasperDesign jasDes;
    String [] data;
    
    
    Guru guru = new Guru();

    /**
     * Creates new form CabekaView
     */
    public CabekaView() {
        initComponents();
        textFields = new ArrayList<>();
        textArea = new ArrayList<>();
        textFields.add(itemNIS);
        textFields.add(itemGuruBk);
        textArea.add(itemPermasalahan);
        textArea.add(itemSolusi);
        textFields.add(itemNamaSiswa);
        textFields.add(tfGuruBk);
        
    }
    
    public void tampilData(String nis){
        dao.getCabekaByNis(nis);
        itemNamaSiswa.setText(dao.getCabekaByNis(nis).getNamaSis());
        itemPermasalahan.setText(dao.getCabekaByNis(nis).getProblem());        
        itemSolusi.setText(dao.getCabekaByNis(nis).getSolution());
        itemGuruBk.setText(dao.getCabekaByNis(nis).getKdGuruBk());
        tfGuruBk.setText(dao.getCabekaByNis(nis).getPetugasBk());
    }
    
    public void tampilNilaiTabel() {
        
    }

    @Override
    public void onDataReceived(String[] data){
        this.data = data;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itemPengampu = new javax.swing.JTextField();
        btnLookupPengampu = new javax.swing.JButton();
        tfPengampu = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemAlamat = new javax.swing.JTextArea();
        itemSemester = new javax.swing.JComboBox<>();
        jenkelPria = new javax.swing.JRadioButton();
        jenkelPria3 = new javax.swing.JRadioButton();
        Kehadiran = new javax.swing.ButtonGroup();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        itemNIS = new javax.swing.JTextField();
        btnLookupNoInduk = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        itemNamaSiswa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        itemGuruBk = new javax.swing.JTextField();
        btnLookupBk = new javax.swing.JButton();
        tfGuruBk = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        itemPermasalahan = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        itemSolusi = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        itemTgl = new com.toedter.calendar.JDateChooser();
        scrCabeka = new javax.swing.JScrollPane();
        tblBk = new javax.swing.JTable();
        kehadiran = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(146, 26, 64));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data Nilai");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("Nama Siswa");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Guru Pengampu");

        btnLookupPengampu.setText("Lookup");
        btnLookupPengampu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupPengampuActionPerformed(evt);
            }
        });

        tfPengampu.setEditable(false);
        tfPengampu.setEnabled(false);

        itemAlamat.setColumns(20);
        itemAlamat.setRows(5);
        jScrollPane1.setViewportView(itemAlamat);

        itemSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "08", "10" }));
        itemSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSemesterActionPerformed(evt);
            }
        });

        jenkelPria.setText("Pria");

        jenkelPria3.setText("Izin");
        jenkelPria3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jenkelPria3ActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        itemNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNISActionPerformed(evt);
            }
        });
        itemNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNISKeyReleased(evt);
            }
        });

        btnLookupNoInduk.setText("Lookup");
        btnLookupNoInduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupNoIndukActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(146, 26, 64));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cabeka");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        itemNamaSiswa.setEditable(false);
        itemNamaSiswa.setEnabled(false);
        itemNamaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNamaSiswaActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("Guru Bk");

        itemGuruBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuruBkActionPerformed(evt);
            }
        });
        itemGuruBk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemGuruBkKeyReleased(evt);
            }
        });

        btnLookupBk.setText("Lookup");
        btnLookupBk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupBkActionPerformed(evt);
            }
        });

        tfGuruBk.setEditable(false);
        tfGuruBk.setEnabled(false);

        itemPermasalahan.setColumns(20);
        itemPermasalahan.setRows(5);
        itemPermasalahan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemPermasalahanKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(itemPermasalahan);

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 102));
        jLabel9.setText("Kehadiran");

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 102));
        jLabel10.setText("Nama Siswa");

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 102));
        jLabel11.setText("Permasalahan");

        itemSolusi.setColumns(20);
        itemSolusi.setRows(5);
        itemSolusi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemSolusiKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(itemSolusi);

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 102));
        jLabel12.setText("Solusi");

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 102));
        jLabel13.setText("NIS");

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 102));
        jLabel14.setText("Tanggal");

        tblBk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblBkMousePressed(evt);
            }
        });
        scrCabeka.setViewportView(tblBk);

        kehadiran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "sakit", "izin", "alpha" }));
        kehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kehadiranActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("Delete");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClear))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnLookupNoInduk)
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(itemTgl, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itemNamaSiswa))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemGuruBk, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnLookupBk)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfGuruBk, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scrCabeka))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(itemNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLookupNoInduk)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(itemTgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemGuruBk)
                    .addComponent(btnLookupBk)
                    .addComponent(tfGuruBk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnClear))
                .addGap(18, 18, 18)
                .addComponent(scrCabeka, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNISActionPerformed
        // TODO add your handling code here:
        //        tblNilai.setModel(dao.getModelNilai(nis, smt));
        tampilData(itemNIS.getText());
        loadData();
    }//GEN-LAST:event_itemNISActionPerformed

    private void itemNISKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNISKeyReleased
        // TODO add your handling code here
        itemNamaSiswa.setText(dao.getNamaSiswa(itemGuruBk.getText()));                                  
        loadData();
    }//GEN-LAST:event_itemNISKeyReleased

    private void btnLookupNoIndukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupNoIndukActionPerformed

        LookupView lookup = new LookupView(this);
        lookup.setTableModel(dao.getLookSiswa());
        lookup.setModal(true);
        lookup.setVisible(true);
        itemNIS.setText(data[0]);
        itemNamaSiswa.setText(data[1]);
        loadData();

    }//GEN-LAST:event_btnLookupNoIndukActionPerformed

    private void itemNamaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNamaSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemNamaSiswaActionPerformed

    private void btnLookupPengampuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupPengampuActionPerformed
        
    }//GEN-LAST:event_btnLookupPengampuActionPerformed

    private void btnLookupBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupBkActionPerformed
        // TODO add your handling code here:
        LookupView lookup = new LookupView(this);
        lookup.setTableModel(dao.getLookguru());
        lookup.setModal(true);
        lookup.setVisible(true);
        itemGuruBk.setText(data[0]);
        tfGuruBk.setText(data[1]);
    }//GEN-LAST:event_btnLookupBkActionPerformed

    private void itemSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSemesterActionPerformed

    private void jenkelPria3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jenkelPria3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jenkelPria3ActionPerformed

    private void itemGuruBkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemGuruBkKeyReleased
        // TODO add your handling code here:
        tfGuruBk.setText(dao.getNamaGuru(itemGuruBk.getText()));                                  
        loadData();
    }//GEN-LAST:event_itemGuruBkKeyReleased

    private void itemPermasalahanKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemPermasalahanKeyReleased
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_itemPermasalahanKeyReleased

    private void itemSolusiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemSolusiKeyReleased
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_itemSolusiKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        itemTgl.setMaxSelectableDate(new java.util.Date());
        loadData();
    }//GEN-LAST:event_formWindowOpened

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (checkFill() == false) {
            JOptionPane.showMessageDialog(this, "Anda belum menginput semuanya");
            return;
        }
        
        if (JOptionPane.showConfirmDialog(null, "Data akan disimpan. Lanjutkan?", "Konfirmasi Simpan Data", 
            JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
            return;
        }

        Cabeka cabeka = new Cabeka();
        cabeka.setNis(itemNIS.getText());
        cabeka.setProblem(itemPermasalahan.getText());
        cabeka.setSolution(itemSolusi.getText());
        cabeka.setKehadiran(kehadiran.getSelectedItem().toString());
        cabeka.setKdGuruBk(itemGuruBk.getText());
        cabeka.setTgl(new java.sql.Date(itemTgl.getDate().getTime()));

        dao.saveCabeka(cabeka);
        loadData();
        removeInput();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        if (confirm("Data akan dihapus", "Hapus Data") == JOptionPane.NO_OPTION) return;
        dao.deleteCabeka(itemNIS.getText(), new java.sql.Date(itemTgl.getDate().getTime()));
        loadData();
        removeInput();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void kehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kehadiranActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_kehadiranActionPerformed

    private void itemGuruBkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuruBkActionPerformed
        // TODO add your handling code here:
        loadData();
    }//GEN-LAST:event_itemGuruBkActionPerformed

    private void tblBkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBkMousePressed
        // TODO add your handling code here:
        int selectedRow = tblBk.rowAtPoint(evt.getPoint());

        if (selectedRow != -1) {
            String nis = tblBk.getValueAt(selectedRow, 0).toString(); 
            String tanggal = tblBk.getValueAt(selectedRow, 2).toString(); 

            loadDataTf(new String[] {nis, "", tanggal});
        }
        loadData();
    }//GEN-LAST:event_tblBkMousePressed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
         if (confirm("Input akan dihapus", "Hapus Input Data") == JOptionPane.NO_OPTION) return;
        removeInput();
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CabekaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CabekaView().setVisible(true);
            }
        });
    }
    
    private void loadData() {
         String tgl = "";
         if (itemTgl.getDate() != null) {
             SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
             tgl = sdf.format(itemTgl.getDate());
         }

         String[] args = {
             itemNIS.getText(),
             tgl
         };

         tblBk.setModel(dao.getModelAllCabeka(args));
         scrCabeka.setViewportView(tblBk);
    }
    
    private void loadDataTf(String [] data) {
        if (data.length < 3) {
            System.out.println("Invalid data array length.");
            return;
        }

        Cabeka cabeka = new Cabeka();
        cabeka.setNis(data[0]);

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        try {
            java.util.Date utilDate = sdf.parse(data[2]);

            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());

            cabeka.setTgl(sqlDate);

        } catch (ParseException e) {
            System.out.println("Date parsing error: " + e.getMessage());
            return;
        }

        this.cabeka = dao.getSingleCabeka(cabeka);

        if (this.cabeka == null) {
            System.out.println("Cabeka not found for NIS: " + data[0]);
            return;
        }
        
        itemNIS.setText(this.cabeka.getNis());
        itemPermasalahan.setText(this.cabeka.getProblem());
        itemSolusi.setText(this.cabeka.getSolution());
        itemGuruBk.setText(this.cabeka.getKdGuruBk());
        kehadiran.setSelectedItem(this.cabeka.getKehadiran());
        itemTgl.setDate(this.cabeka.getTgl());

        itemNamaSiswa.setText(this.cabeka.getSiswa().getNama());
        tfGuruBk.setText(this.cabeka.getGuru().getNama());
    }
    
     private void removeInput() {
        for (JTextField textField : textFields) {
            textField.setText("");
        }
        
        for (JTextArea textArea : textArea) {
            textArea.setText("");
        }

        if (kehadiran != null) {
            kehadiran.setSelectedItem(null); 
        }

        if (itemTgl != null) {
            itemTgl.setDate(null);
        }
    }
     
     public boolean checkFill() {
        for (JTextField textField : textFields) {
            if (textField.getText().isEmpty()) {
                return false;
            }
        }
        
        for (JTextArea textArea : textArea) {
            if (textArea.getText().isEmpty()) {
                return false;
            }
        }
        
        if (kehadiran.getSelectedItem() == null) {
            return false;
        }
        if (itemTgl.getDate() == null) {
            return false;
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Kehadiran;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLookupBk;
    private javax.swing.JButton btnLookupNoInduk;
    private javax.swing.JButton btnLookupPengampu;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextArea itemAlamat;
    public static javax.swing.JTextField itemGuruBk;
    public static javax.swing.JTextField itemNIS;
    public static javax.swing.JTextField itemNamaSiswa;
    public static javax.swing.JTextField itemPengampu;
    private javax.swing.JTextArea itemPermasalahan;
    private javax.swing.JComboBox<String> itemSemester;
    private javax.swing.JTextArea itemSolusi;
    private com.toedter.calendar.JDateChooser itemTgl;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JRadioButton jenkelPria;
    private javax.swing.JRadioButton jenkelPria3;
    private javax.swing.JComboBox<String> kehadiran;
    private javax.swing.JScrollPane scrCabeka;
    private javax.swing.JTable tblBk;
    public static javax.swing.JTextField tfGuruBk;
    public static javax.swing.JTextField tfPengampu;
    // End of variables declaration//GEN-END:variables

    private int confirm(String text, String title) {
        return JOptionPane.showOptionDialog(null, text, title, JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
    }
}
