/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIew;

import DAO.NilaiDAO;
import java.sql.Date;
import static Connection.connection.getConnection;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Guru;
import model.Jurusan;
import model.Mapel;
import model.Nilai;
import model.Siswa;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author TUF GAMING F15
 */
public class NilaiView extends javax.swing.JFrame {
    
    NilaiDAO dao = new NilaiDAO();
    PreparedStatement ps;
    ResultSet rs;
    Siswa siswa = new Siswa();
    Nilai nilai = new Nilai();
    JasperReport jasRep;
    JasperPrint jasPrint;
    JasperDesign jasDes;
    
    Mapel mapel = new Mapel();
    Guru guru = new Guru();
    Jurusan jurusan = new Jurusan();

    /**
     * Creates new form DKK
     */
    public NilaiView() {
        initComponents();
    }
    
    public void tampilData(String nis){
        dao.getSiswaByNis(nis);
        itemNamaSiswa.setText(dao.getSiswaByNis(nis).getNama());
        itemMapel.setText(dao.getSiswaByNis(nis).getKdMapel());
        tfMapel.setText(dao.getSiswaByNis(nis).getMapel());
        tfPengampu.setText(dao.getSiswaByNis(nis).getPengampu());
        itemPengampu.setText(dao.getSiswaByNis(nis).getKdGuru());
        itemNilai.setText(String.valueOf(dao.getSiswaByNis(nis).getNilai()));
    }
    
    public void tampilNilaiTabel() {
        tblNilai.setModel(dao.getModelNilai(itemNIS.getText(), itemSemester.getSelectedItem().toString()));
        scrNilai.setViewportView(tblNilai);
        
        tblNilai.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        tblNilai.getColumnModel().getColumn(0).setPreferredWidth(40);        
        tblNilai.getColumnModel().getColumn(1).setPreferredWidth(170);
        tblNilai.getColumnModel().getColumn(2).setPreferredWidth(40);
        tblNilai.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblNilai.getColumnModel().getColumn(4).setPreferredWidth(170);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemNIS = new javax.swing.JTextField();
        btnLookupNoInduk = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        itemMapel = new javax.swing.JTextField();
        itemNilai = new javax.swing.JTextField();
        itemPengampu = new javax.swing.JTextField();
        btnLookupPengampu = new javax.swing.JButton();
        btnLookupMapel = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnCetak = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        scrNilai = new javax.swing.JScrollPane();
        tblNilai = new javax.swing.JTable();
        itemSemester = new javax.swing.JComboBox<>();
        itemNamaSiswa = new javax.swing.JTextField();
        tfPengampu = new javax.swing.JTextField();
        tfMapel = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(146, 26, 64));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Nilai");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("Nomor Induk");

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 102));
        jLabel4.setText("Semester");

        itemNIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNISActionPerformed(evt);
            }
        });
        itemNIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemNISKeyReleased(evt);
            }
        });

        btnLookupNoInduk.setText("Lookup");
        btnLookupNoInduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupNoIndukActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("Nama Siswa");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 102));
        jLabel6.setText("Matapelajaran");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 102));
        jLabel7.setText("Guru Pengampu");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 102));
        jLabel8.setText("Nilai");

        btnLookupPengampu.setText("Lookup");
        btnLookupPengampu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupPengampuActionPerformed(evt);
            }
        });

        btnLookupMapel.setText("Lookup");
        btnLookupMapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLookupMapelActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCetak.setText("Cetak Raport");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tblNilai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblNilai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNilaiMouseClicked(evt);
            }
        });
        scrNilai.setViewportView(tblNilai);

        itemSemester.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "08", "10" }));
        itemSemester.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSemesterActionPerformed(evt);
            }
        });

        itemNamaSiswa.setEditable(false);
        itemNamaSiswa.setEnabled(false);

        tfPengampu.setEditable(false);
        tfPengampu.setEnabled(false);

        tfMapel.setEditable(false);
        tfMapel.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemNIS, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLookupNoInduk)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(itemSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(itemNamaSiswa)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(itemMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLookupMapel)
                                .addGap(18, 18, 18)
                                .addComponent(tfMapel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(itemNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(itemPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnLookupPengampu)))
                                .addGap(18, 18, 18)
                                .addComponent(tfPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCetak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSimpan))
                    .addComponent(scrNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 595, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(itemNIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLookupNoInduk)
                    .addComponent(jLabel4)
                    .addComponent(itemSemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(itemNamaSiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itemMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnLookupMapel))
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(itemPengampu)
                                .addComponent(btnLookupPengampu))
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(itemNilai)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(tfMapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPengampu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnSimpan)
                    .addComponent(btnCetak))
                .addGap(18, 18, 18)
                .addComponent(scrNilai, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
//        tblNilai.setModel(dao.getLookNilai());
//        scrNilai.setViewportView(tblNilai);
    }//GEN-LAST:event_formWindowOpened

    private void itemNISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNISActionPerformed
        // TODO add your handling code here:
//        tblNilai.setModel(dao.getModelNilai(nis, smt));
        tampilData(itemNIS.getText());
    }//GEN-LAST:event_itemNISActionPerformed

    private void itemNISKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemNISKeyReleased
        // TODO add your handling code here
        tampilData(itemNIS.getText());
    }//GEN-LAST:event_itemNISKeyReleased

    private void btnLookupNoIndukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupNoIndukActionPerformed

        LookupView lookup = new LookupView(this);
        lookup.setModal(true);
        LookupView.lookupTxt.setText("Data Siswa");
        LookupView.tabelLookup.setModel(dao.getLookSiswa());        
        LookupView.scrLookup.setViewportView(LookupView.tabelLookup);
        lookup.setVisible(true);
        tampilNilaiTabel();
    }//GEN-LAST:event_btnLookupNoIndukActionPerformed

    private void btnLookupMapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupMapelActionPerformed
        // TODO add your handling code here:

        LookupView lookup = new LookupView(this);
        lookup.setModal(true);
        LookupView.lookupTxt.setText("Data Mapel");        
        LookupView.tabelLookup.setModel(dao.getLookMapel());        
        LookupView.scrLookup.setViewportView(LookupView.tabelLookup);
        lookup.setVisible(true);
        tampilNilaiTabel();
    }//GEN-LAST:event_btnLookupMapelActionPerformed

    private void btnLookupPengampuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLookupPengampuActionPerformed
        // TODO add your handling code here:

        LookupView lookup = new LookupView(this);
        lookup.setModal(true);
        LookupView.lookupTxt.setText("Data Pengampu");        
        LookupView.tabelLookup.setModel(dao.getLookguru());        
        LookupView.scrLookup.setViewportView(LookupView.tabelLookup);
        lookup.setVisible(true);
        tampilNilaiTabel();
    }//GEN-LAST:event_btnLookupPengampuActionPerformed

    private void tblNilaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNilaiMouseClicked
        // TODO add your handling code here:
        itemNIS.setText(tblNilai.getValueAt(tblNilai.getSelectedRow(), 0).toString());
        tampilData(itemNIS.getText());
    }//GEN-LAST:event_tblNilaiMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        if (itemNamaSiswa.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Data Siswa Harus Diisi...");
        else if (itemSemester.getSelectedItem().equals(""))
            JOptionPane.showMessageDialog(null, "Semester Harus Diisi...");
        else if (itemMapel.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Matapelajaran Harus Diisi...");
        else if (itemPengampu.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Guru Pnegampu Harus Diisi...");
        else if (itemNilai.getText().trim().equals(""))
            JOptionPane.showMessageDialog(null, "Nilai Harus Diisi");
        else {
            int pilihan = JOptionPane.showOptionDialog(null, "Data Akan Disimpan ?", 
                    "Simpan Data", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            
            if (pilihan == JOptionPane.YES_OPTION){
                nilai.setNis(itemNIS.getText().trim());
                nilai.setKdGuru(itemPengampu.getText().trim());
                nilai.setKdMapel(itemMapel.getText().trim());
                nilai.setNilai(Double.valueOf(itemNilai.getText()));
                nilai.setSmt(itemSemester.getSelectedItem().toString());
                dao.SimpanNilai(nilai);
                tampilNilaiTabel();
            }
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void itemSemesterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSemesterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemSemesterActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String nis = itemNIS.getText().trim();
        String smt = itemSemester.getSelectedItem().toString().trim();
        String kdMapel = itemMapel.getText().trim();

        if (nis.isEmpty()) {
            JOptionPane.showMessageDialog(null, "NIS harus diisi.");
        } else if (smt.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Semester harus diisi.");
        } else if (kdMapel.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Kode Mata Pelajaran harus diisi.");
        } else {
            int pilihan = JOptionPane.showConfirmDialog(null, 
                    "Apakah Anda yakin ingin menghapus data ini?", 
                    "Konfirmasi Hapus Data", 
                    JOptionPane.YES_NO_OPTION, 
                    JOptionPane.QUESTION_MESSAGE);

            if (pilihan == JOptionPane.YES_OPTION) {
                dao.DeleteNilai(nis, smt, kdMapel);
                tampilNilaiTabel();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
//        // TODO add your handling code here:
        Map<String,Object> para = new HashMap<>();
        para.put("nis", itemNIS.getText());
        para.put("smt", itemSemester.getSelectedItem().toString());
        try {
//            File report = new File("src/report/RepNilai.jrxml");
//            jasDes = JRXmlLoader.load(report);
//            jasRep = JasperCompileManager.compileReport(jasDes);
//            jasPrint =JasperFillManager.fillReport(jasRep,para,Connection.connection.getConnection());
//            JasperViewer.viewReport(jasPrint,true);
        }
       catch(Exception e) {
           JOptionPane.showMessageDialog(null, "Gagal Membuka Laporan : "+e,
                   "Cetak Laporan", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
//        StringBuilder rtfContent = new StringBuilder();
//            try {
//                // Header dokumen RTF
//                rtfContent.append("{\\rtf1\\ansi\\deff0");
//                rtfContent.append("\\b\\fs32 RAPOR SISWA \\b0\\fs24\\par\\par"); // Judul
//
//                // Informasi siswa
//                rtfContent.append("\\trowd\\trgaph108\\cellx2000 ");
//                rtfContent.append("NIK: ").append(itemNIS.getText()).append("\\cell\\row");
//                rtfContent.append("\\trowd\\trgaph108\\cellx5000 ");
//                rtfContent.append("Nama Siswa: ").append(itemNamaSiswa.getText()).append("\\cell\\row");
//                rtfContent.append("\\trowd\\trgaph108\\cellx2000 ");
//                rtfContent.append("Semester: ").append(itemSemester.getSelectedItem().toString()).append("\\cell\\row\\par");
//                // Header tabel nilai
//                rtfContent.append("\\trowd\\trgaph108");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx2000 \\b Mapel\\b0\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx4000 \\b Nama Mapel\\b0\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx6000 \\b Nilai\\b0\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx8000 \\b Kode Guru\\b0\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx10000 \\b Nama Guru\\b0\\cell\\row");
//
//
//                // Isi tabel nilai
//             for (int i = 0; i < tblNilai.getRowCount(); i++) {
//                String kodeMapel = (tblNilai.getValueAt(i, 0) != null) ? tblNilai.getValueAt(i, 0).toString() : "-";
//                String namaMapel = (tblNilai.getValueAt(i, 1) != null) ? tblNilai.getValueAt(i, 1).toString() : "-";
//                String nilai = (tblNilai.getValueAt(i, 2) != null) ? tblNilai.getValueAt(i, 2).toString().replace(".0", "") : "-";
//                String kodeGuru = (tblNilai.getValueAt(i, 3) != null) ? tblNilai.getValueAt(i, 3).toString() : "-";
//                String namaGuru = (tblNilai.getValueAt(i, 4) != null) ? tblNilai.getValueAt(i, 4).toString() : "-";
//
//                // Menambahkan data setiap baris ke dalam tabel
//                rtfContent.append("\\trowd\\trgaph108");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx2000 ").append(kodeMapel).append("\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx4000 ").append(namaMapel).append("\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx6000 ").append(nilai).append("\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx8000 ").append(kodeGuru).append("\\cell");
//                rtfContent.append("\\clbrdrt\\brdrs\\brdrw10\\clbrdrl\\brdrs\\brdrw10\\clbrdrb\\brdrs\\brdrw10\\clbrdrr\\brdrs\\brdrw10\\cellx10000 ").append(namaGuru).append("\\cell\\row");
//                }
//
//
//                // Akhiri dokumen RTF
//                rtfContent.append("}");
//
//                // Buat file sementara
//                File tempFile = File.createTempFile("Rapor_Siswa_", ".rtf");
//                tempFile.deleteOnExit(); // File otomatis dihapus saat program selesai
//
//                try (FileWriter writer = new FileWriter(tempFile)) {
//                    writer.write(rtfContent.toString());
//                }
//
//                // Buka file langsung
//                if (Desktop.isDesktopSupported()) {
//                    Desktop.getDesktop().open(tempFile);
//                } else {
//                    JOptionPane.showMessageDialog(this, "Tidak dapat membuka file RTF.");
//                }
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mencetak rapor: " + e.getMessage());
//                e.printStackTrace();
//            }
    }//GEN-LAST:event_btnCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NilaiView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnLookupMapel;
    private javax.swing.JButton btnLookupNoInduk;
    private javax.swing.JButton btnLookupPengampu;
    private javax.swing.JButton btnSimpan;
    public static javax.swing.JTextField itemMapel;
    public static javax.swing.JTextField itemNIS;
    public static javax.swing.JTextField itemNamaSiswa;
    public static javax.swing.JTextField itemNilai;
    public static javax.swing.JTextField itemPengampu;
    private javax.swing.JComboBox<String> itemSemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JScrollPane scrNilai;
    private javax.swing.JTable tblNilai;
    public static javax.swing.JTextField tfMapel;
    public static javax.swing.JTextField tfPengampu;
    // End of variables declaration//GEN-END:variables
}
